-- =============================================================================
-- PE Partners - Snowflake Setup Script
-- Run this script in your Snowflake account to create all required objects
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- 1. DATABASE AND SCHEMA
-- =============================================================================

CREATE DATABASE IF NOT EXISTS PEPARTNERS_DB;
CREATE SCHEMA IF NOT EXISTS PEPARTNERS_DB.CORE;
USE SCHEMA PEPARTNERS_DB.CORE;

-- =============================================================================
-- 2. WAREHOUSES
-- =============================================================================

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

-- =============================================================================
-- 3. IMAGE REPOSITORY AND COMPUTE POOL
-- =============================================================================

CREATE IMAGE REPOSITORY IF NOT EXISTS PEPARTNERS_DB.CORE.PE_REPO;

CREATE COMPUTE POOL IF NOT EXISTS PE_APP_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 3600;

-- =============================================================================
-- 4. EXTERNAL ACCESS INTEGRATION (for outbound network)
-- =============================================================================

CREATE NETWORK RULE IF NOT EXISTS PEPARTNERS_DB.CORE.PE_SNOWFLAKE_RULE
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS PE_SNOWFLAKE_EAI
  ALLOWED_NETWORK_RULES = (PEPARTNERS_DB.CORE.PE_SNOWFLAKE_RULE)
  ENABLED = TRUE;

-- =============================================================================
-- 5. STAGING TABLES (source of truth - writable)
-- =============================================================================

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.FUNDS_STG (
  FUND_ID NUMBER(38,0),
  FUND_NAME VARCHAR(200),
  STRATEGY VARCHAR(100),
  TOTAL_AUM_GBP NUMBER(20,2),
  MANAGEMENT_FEE_PCT NUMBER(5,2),
  PERFORMANCE_FEE_PCT NUMBER(5,2),
  INCEPTION_DATE DATE,
  FUND_STATUS VARCHAR(50),
  MINIMUM_INVESTMENT_GBP NUMBER(20,2)
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.CUSTOMERS_STG (
  CUSTOMER_ID NUMBER(38,0),
  FULL_NAME VARCHAR(200),
  COMPANY_NAME VARCHAR(200),
  INVESTOR_TYPE VARCHAR(100),
  REGION VARCHAR(100),
  AUM_COMMITMENT_GBP NUMBER(20,2),
  EMAIL VARCHAR(200),
  PHONE VARCHAR(50),
  ONBOARDED_DATE DATE,
  STATUS VARCHAR(50),
  RISK_PROFILE VARCHAR(50),
  RELATIONSHIP_MANAGER VARCHAR(200)
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.INVESTMENTS_STG (
  INVESTMENT_ID NUMBER(38,0),
  FUND_ID NUMBER(38,0),
  SECURITY_NAME VARCHAR(200),
  TICKER VARCHAR(20),
  SECTOR VARCHAR(100),
  POSITION_TYPE VARCHAR(50),
  MARKET_VALUE_GBP NUMBER(20,2),
  WEIGHT_PCT NUMBER(5,2),
  GEOGRAPHY VARCHAR(100),
  ENTRY_DATE DATE
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.FUND_PERFORMANCE_STG (
  PERF_ID NUMBER(38,0),
  FUND_ID NUMBER(38,0),
  REPORTING_DATE DATE,
  MONTHLY_RETURN_PCT NUMBER(8,4),
  YTD_RETURN_PCT NUMBER(8,4),
  SHARPE_RATIO NUMBER(6,3),
  MAX_DRAWDOWN_PCT NUMBER(8,4),
  VOLATILITY_PCT NUMBER(8,4)
);

-- =============================================================================
-- 6. DOCUMENT & CALL TABLES
-- =============================================================================

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS (
  FILING_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  COMPANY_NAME VARCHAR(200),
  TICKER VARCHAR(20),
  FORM_TYPE VARCHAR(50),
  FILING_CATEGORY VARCHAR(100),
  FILING_DATE DATE,
  SOURCE_URL VARCHAR(500),
  FILING_TITLE VARCHAR(500)
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_CHUNKS (
  CHUNK_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  FILING_ID NUMBER(38,0),
  COMPANY_NAME VARCHAR(200),
  TICKER VARCHAR(20),
  FORM_TYPE VARCHAR(50),
  FILING_CATEGORY VARCHAR(100),
  FILING_DATE DATE,
  CHUNK_TEXT VARCHAR(4000),
  CHUNK_INDEX NUMBER(38,0)
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_TEXT (
  FILING_ID NUMBER(38,0),
  FULL_TEXT VARCHAR,
  DOCUMENT_PATH VARCHAR,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_ANALYSIS (
  FILING_ID NUMBER(38,0),
  SUMMARY VARCHAR,
  SENTIMENT_JSON VARIANT,
  GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.COMPANY_CALLS (
  CALL_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  COMPANY_NAME VARCHAR(200),
  TICKER VARCHAR(20),
  CALL_TYPE VARCHAR(100),
  CALL_DATE DATE,
  CALL_TITLE VARCHAR(500),
  DURATION_MINUTES NUMBER(38,0),
  PARTICIPANTS VARCHAR(1000),
  TRANSCRIPT_SUMMARY VARCHAR(5000),
  VIDEO_FILENAME VARCHAR(200),
  SENTIMENT VARCHAR(50),
  SENTIMENT_SCORE NUMBER(5,2),
  TRANSCRIPT VARCHAR(50000)
);

-- =============================================================================
-- 7. REPORT SCHEDULES TABLE
-- =============================================================================

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.PE_REPORT_SCHEDULES (
  SCHEDULE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  FUND_ID NUMBER(38,0),
  FUND_NAME VARCHAR(200),
  RECIPIENT_EMAIL VARCHAR(200),
  FREQUENCY VARCHAR(50),
  CRON_EXPR VARCHAR(100),
  TASK_NAME VARCHAR(200),
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_BY VARCHAR(200),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- 8. INTERACTIVE TABLES (low-latency serving layer)
-- =============================================================================

CREATE OR REPLACE INTERACTIVE TABLE PEPARTNERS_DB.CORE.FUNDS_IT
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = COMPUTE_WH
  AS SELECT * FROM PEPARTNERS_DB.CORE.FUNDS_STG;

CREATE OR REPLACE INTERACTIVE TABLE PEPARTNERS_DB.CORE.CUSTOMERS_IT
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = COMPUTE_WH
  AS SELECT * FROM PEPARTNERS_DB.CORE.CUSTOMERS_STG;

CREATE OR REPLACE INTERACTIVE TABLE PEPARTNERS_DB.CORE.INVESTMENTS_IT
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = COMPUTE_WH
  AS SELECT * FROM PEPARTNERS_DB.CORE.INVESTMENTS_STG;

CREATE OR REPLACE INTERACTIVE TABLE PEPARTNERS_DB.CORE.FUND_PERFORMANCE_IT
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = COMPUTE_WH
  AS SELECT * FROM PEPARTNERS_DB.CORE.FUND_PERFORMANCE_STG;
