-- =============================================================================
-- PE Partners - Documents Search Pipeline
-- Run AFTER 01_ddl.sql and AFTER uploading PDFs to @PEPARTNERS_DB.CORE.DOCUMENTS_STAGE
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE SCHEMA PEPARTNERS_DB.CORE;
USE WAREHOUSE COMPUTE_WH;

CREATE STAGE IF NOT EXISTS PEPARTNERS_DB.CORE.DOCUMENTS_STAGE
  DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE TABLE PEPARTNERS_DB.CORE.DOCUMENTS_RAW (
  DOCUMENT_PATH VARCHAR NOT NULL,
  DOCUMENT_NAME VARCHAR NOT NULL,
  DOCUMENT_URL VARCHAR,
  DOCUMENT_TYPE VARCHAR,
  COMPANY_NAME VARCHAR,
  TICKER VARCHAR,
  FORM_TYPE VARCHAR,
  FILING_CATEGORY VARCHAR,
  FILING_DATE DATE,
  RAW_TEXT VARCHAR,
  LAST_MODIFIED TIMESTAMP_NTZ,
  FILE_SIZE NUMBER,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DOCUMENT_PATH)
);

TRUNCATE TABLE PEPARTNERS_DB.CORE.DOCUMENTS_RAW;
TRUNCATE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS;
TRUNCATE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_CHUNKS;
TRUNCATE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_TEXT;
TRUNCATE TABLE PEPARTNERS_DB.CORE.COMPANY_FILINGS_ANALYSIS;

INSERT INTO PEPARTNERS_DB.CORE.DOCUMENTS_RAW (
  DOCUMENT_PATH,
  DOCUMENT_NAME,
  DOCUMENT_URL,
  DOCUMENT_TYPE,
  COMPANY_NAME,
  TICKER,
  FORM_TYPE,
  FILING_CATEGORY,
  FILING_DATE,
  RAW_TEXT,
  LAST_MODIFIED,
  FILE_SIZE
)
SELECT
  RELATIVE_PATH,
  SPLIT_PART(RELATIVE_PATH, '/', -1) AS DOCUMENT_NAME,
  BUILD_STAGE_FILE_URL('@PEPARTNERS_DB.CORE.DOCUMENTS_STAGE', RELATIVE_PATH) AS DOCUMENT_URL,
  'PDF' AS DOCUMENT_TYPE,
  INITCAP(REPLACE(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 1), '^[^-]+'), '_', ' ')) AS COMPANY_NAME,
  UPPER(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 1), '[^-]+$')) AS TICKER,
  UPPER(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 2), '(^[^_]+)')) AS FORM_TYPE,
  CASE
    WHEN UPPER(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 2), '(^[^_]+)')) = '10K' THEN 'Annual Report'
    WHEN UPPER(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 2), '(^[^_]+)')) = '8K' THEN 'Current Report'
    ELSE 'Annual Report'
  END AS FILING_CATEGORY,
  TRY_TO_DATE(REGEXP_SUBSTR(SPLIT_PART(SPLIT_PART(RELATIVE_PATH, '/', -1), '__', 2), '(\\d{4}-\\d{2}-\\d{2})')) AS FILING_DATE,
  TO_VARCHAR(SNOWFLAKE.CORTEX.PARSE_DOCUMENT('@PEPARTNERS_DB.CORE.DOCUMENTS_STAGE', RELATIVE_PATH, OBJECT_CONSTRUCT('mode', 'OCR')):content) AS RAW_TEXT,
  LAST_MODIFIED,
  SIZE
FROM DIRECTORY('@PEPARTNERS_DB.CORE.DOCUMENTS_STAGE')
WHERE LOWER(RELATIVE_PATH) LIKE '%.pdf';

INSERT INTO PEPARTNERS_DB.CORE.COMPANY_FILINGS (
  COMPANY_NAME,
  TICKER,
  FORM_TYPE,
  FILING_CATEGORY,
  FILING_DATE,
  SOURCE_URL,
  FILING_TITLE
)
SELECT
  COMPANY_NAME,
  TICKER,
  FORM_TYPE,
  FILING_CATEGORY,
  COALESCE(FILING_DATE, CURRENT_DATE()),
  DOCUMENT_URL,
  DOCUMENT_NAME
FROM PEPARTNERS_DB.CORE.DOCUMENTS_RAW
ORDER BY DOCUMENT_PATH;

INSERT INTO PEPARTNERS_DB.CORE.COMPANY_FILINGS_TEXT (FILING_ID, FULL_TEXT, DOCUMENT_PATH)
SELECT
  filings.FILING_ID,
  raw.RAW_TEXT,
  raw.DOCUMENT_PATH
FROM PEPARTNERS_DB.CORE.COMPANY_FILINGS AS filings
JOIN PEPARTNERS_DB.CORE.DOCUMENTS_RAW AS raw
  ON filings.SOURCE_URL = raw.DOCUMENT_URL;

INSERT INTO PEPARTNERS_DB.CORE.COMPANY_FILINGS_CHUNKS (
  FILING_ID,
  COMPANY_NAME,
  TICKER,
  FORM_TYPE,
  FILING_CATEGORY,
  FILING_DATE,
  CHUNK_TEXT,
  CHUNK_INDEX
)
WITH chunked AS (
  SELECT
    filings.FILING_ID,
    filings.COMPANY_NAME,
    filings.TICKER,
    filings.FORM_TYPE,
    filings.FILING_CATEGORY,
    filings.FILING_DATE,
    chunks.INDEX AS CHUNK_INDEX,
    chunks.VALUE::VARCHAR AS CHUNK_TEXT
  FROM PEPARTNERS_DB.CORE.COMPANY_FILINGS AS filings
  JOIN PEPARTNERS_DB.CORE.COMPANY_FILINGS_TEXT AS texts
    ON filings.FILING_ID = texts.FILING_ID
  ,
  LATERAL FLATTEN(
    INPUT => SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
      texts.FULL_TEXT,
      'markdown',
      1500,
      250
    )
  ) AS chunks
)
SELECT
  FILING_ID,
  COMPANY_NAME,
  TICKER,
  FORM_TYPE,
  FILING_CATEGORY,
  FILING_DATE,
  CHUNK_TEXT,
  CHUNK_INDEX
FROM chunked
WHERE CHUNK_TEXT IS NOT NULL
  AND LENGTH(TRIM(CHUNK_TEXT)) > 0;

INSERT INTO PEPARTNERS_DB.CORE.COMPANY_FILINGS_ANALYSIS (FILING_ID, SUMMARY, SENTIMENT_JSON)
SELECT
  filings.FILING_ID,
  SNOWFLAKE.CORTEX.SUMMARIZE(texts.FULL_TEXT) AS SUMMARY,
  PARSE_JSON(
    SNOWFLAKE.CORTEX.COMPLETE(
      'openai-gpt-5.4-mini',
      CONCAT(
        'Return strict JSON with shape {"categories":[{"name":"overall","sentiment":"Positive|Neutral|Negative|Mixed"}],"rationale":"..."}. Analyze this filing: ',
        LEFT(texts.FULL_TEXT, 120000)
      ),
      OBJECT_CONSTRUCT('temperature', 0)
    )
  ) AS SENTIMENT_JSON
FROM PEPARTNERS_DB.CORE.COMPANY_FILINGS AS filings
JOIN PEPARTNERS_DB.CORE.COMPANY_FILINGS_TEXT AS texts
  ON filings.FILING_ID = texts.FILING_ID;

CREATE OR REPLACE CORTEX SEARCH SERVICE PEPARTNERS_DB.CORE.COMPANY_FILINGS_SEARCH_SERVICE
  ON CHUNK_TEXT
  ATTRIBUTES COMPANY_NAME, TICKER, FORM_TYPE, FILING_CATEGORY, FILING_DATE, FILING_ID
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT
      FILING_ID,
      COMPANY_NAME,
      TICKER,
      FORM_TYPE,
      FILING_CATEGORY,
      FILING_DATE,
      CHUNK_TEXT
    FROM PEPARTNERS_DB.CORE.COMPANY_FILINGS_CHUNKS
  );